spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop #;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create # application실행 시점에 table을 삭제 및 재생성 옵션
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
